// Known baby/child product brands and their parent companies. Used to widen
// recall-relevance filtering beyond generic category keywords ("stroller",
// "car seat") — a lot of CPSC/FDA recall titles name the brand or parent
// corporation without using any of those generic terms at all
// (e.g. "Newell Brands Recalls Graco..." never says "stroller").
//
// Keep this deduplicated and lowercase-comparable; matching is a simple
// substring check against recall text, same as BABY_KEYWORDS.
export const BABY_BRANDS: { brand: string; parent: string }[] = [
  { brand: "Graco", parent: "Newell Brands" },
  { brand: "Chicco", parent: "Artsana Group" },
  { brand: "Nuna", parent: "Nuna International BV" },
  { brand: "UPPAbaby", parent: "UPPAbaby, LLC" },
  { brand: "Britax", parent: "Britax Group" },
  { brand: "Evenflo", parent: "Goodbaby International" },
  { brand: "Baby Jogger", parent: "Newell Brands" },
  { brand: "Bugaboo", parent: "Bugaboo International BV" },
  { brand: "Cybex", parent: "Goodbaby International" },
  { brand: "Maxi-Cosi", parent: "Dorel Juvenile" },
  { brand: "Doona", parent: "Doona USA / Simple Parenting" },
  { brand: "Peg Perego", parent: "Peg Perego S.p.A." },
  { brand: "Joie", parent: "Wonderland Group" },
  { brand: "Baby Trend", parent: "Baby Trend Inc." },
  { brand: "BOB Gear", parent: "Britax Group" },
  { brand: "Thule", parent: "Thule Group" },
  { brand: "Inglesina", parent: "Inglesina Baby S.p.A." },
  { brand: "Joolz", parent: "Joolz BV" },
  { brand: "Colugo", parent: "Colugo" },
  { brand: "Mockingbird", parent: "Mockingbird" },
  { brand: "Babyark", parent: "Babyark" },
  { brand: "Clek", parent: "Clek Inc." },
  { brand: "Diono", parent: "Diono LLC" },
  { brand: "Silver Cross", parent: "Silver Cross" },
  { brand: "Larktale", parent: "Larktale" },
  { brand: "Veer", parent: "Veer Gear" },
  { brand: "WonderFold", parent: "WonderFold" },
  { brand: "BabyBjörn", parent: "BabyBjörn AB" },
  { brand: "Ergobaby", parent: "Ergobaby" },
  { brand: "Boba", parent: "Boba Inc." },
  { brand: "WildBird", parent: "WildBird" },
  { brand: "LÍLLÉbaby", parent: "Thrive International" },
  { brand: "Moby", parent: "Thrive International" },
  { brand: "Infantino", parent: "Infantino LLC" },
  { brand: "KeaBabies", parent: "KeaBabies" },
  { brand: "Konny", parent: "Konny" },
  { brand: "HALO", parent: "Halo Innovations" },
  { brand: "Happiest Baby", parent: "Happiest Baby Inc." },
  { brand: "Newton Baby", parent: "Newton Baby" },
  { brand: "babyletto", parent: "Million Dollar Baby Co." },
  { brand: "DaVinci", parent: "Million Dollar Baby Co." },
  { brand: "Delta Children", parent: "Delta Children" },
  { brand: "Dream On Me", parent: "Dream On Me" },
  { brand: "Stokke", parent: "Stokke AS" },
  { brand: "Naturepedic", parent: "Naturepedic" },
  { brand: "Simmons Kids", parent: "Delta Children" },
  { brand: "Baby Delight", parent: "Baby Delight" },
  { brand: "Arm's Reach", parent: "Arm's Reach Concepts" },
  { brand: "Cradlewise", parent: "Cradlewise Inc." },
  { brand: "Oeuf", parent: "Oeuf LLC" },
  { brand: "Nursery Works", parent: "Million Dollar Baby Co." },
  { brand: "Philips Avent", parent: "Philips" },
  { brand: "Dr. Brown's", parent: "Handi-Craft Company" },
  { brand: "Comotomo", parent: "Comotomo Inc." },
  { brand: "Tommee Tippee", parent: "Mayborn Group" },
  { brand: "MAM", parent: "MAM Baby" },
  { brand: "Boon", parent: "TOMY International" },
  { brand: "OXO Tot", parent: "OXO" },
  { brand: "Béaba", parent: "Béaba" },
  { brand: "Baby Brezza", parent: "Baby Brezza" },
  { brand: "ezpz", parent: "ezpz" },
  { brand: "Hegen", parent: "Hegen" },
  { brand: "Nanobébé", parent: "Nanobébé" },
  { brand: "BIBS", parent: "BIBS Denmark" },
  { brand: "Mushie", parent: "" },
  { brand: "Medela", parent: "Medela AG" },
  { brand: "Lansinoh", parent: "Pigeon Corporation" },
  { brand: "Elvie", parent: "Elvie" },
  { brand: "Momcozy", parent: "Momcozy" },
  { brand: "Haakaa", parent: "Haakaa" },
  { brand: "Kiinde", parent: "Kiinde" },
  { brand: "Pigeon", parent: "Pigeon Corporation" },
  { brand: "NUK", parent: "Newell Brands" },
  { brand: "Similac", parent: "Abbott" },
  { brand: "Enfamil", parent: "Reckitt" },
  { brand: "Bobbie", parent: "Bobbie" },
  { brand: "Kendamil", parent: "Kendal Nutricare" },
  { brand: "Gerber", parent: "Nestlé" },
  { brand: "Happy Baby Organics", parent: "Danone" },
  { brand: "Earth's Best", parent: "Hain Celestial" },
  { brand: "Serenity Kids", parent: "Serenity Kids" },
  { brand: "Little Spoon", parent: "Little Spoon" },
  { brand: "Once Upon a Farm", parent: "Once Upon a Farm" },
  { brand: "Pampers", parent: "Procter & Gamble" },
  { brand: "Huggies", parent: "Kimberly-Clark" },
  { brand: "Coterie", parent: "Coterie" },
  { brand: "DYPER", parent: "DYPER" },
  { brand: "Millie Moon", parent: "Millennium Babycare" },
  { brand: "The Honest Company", parent: "The Honest Company" },
  { brand: "WaterWipes", parent: "Irish Breeze Ltd." },
  { brand: "Fisher-Price", parent: "Mattel" },
  { brand: "Lovevery", parent: "Lovevery" },
  { brand: "Melissa & Doug", parent: "Spin Master" },
  { brand: "Skip Hop", parent: "Carter's Inc." },
  { brand: "Tiny Love", parent: "Dorel Juvenile" },
  { brand: "Baby Einstein", parent: "Kids2" },
  { brand: "Bright Starts", parent: "Kids2" },
  { brand: "Ingenuity", parent: "Kids2" },
  { brand: "Manhattan Toy", parent: "Manhattan Toy Company" },
  { brand: "Hape", parent: "Hape International" },
  { brand: "VTech", parent: "VTech Holdings" },
  { brand: "Lamaze", parent: "TOMY International" },
  { brand: "Janod", parent: "Juratoys" },
  { brand: "HABA", parent: "HABA Familygroup" },
  { brand: "Cloud b", parent: "Cloud b" },
  { brand: "Frida Baby", parent: "Frida" },
  { brand: "Owlet", parent: "Owlet, Inc." },
  { brand: "Nanit", parent: "Nanit" },
  { brand: "Motorola Nursery", parent: "Binatone Global" },
  { brand: "Babysense", parent: "Hisense Ltd." },
  { brand: "Safety 1st", parent: "Dorel Juvenile" },
  { brand: "Dreambaby", parent: "Tee-Zed Products" },
  { brand: "Regalo", parent: "Regalo International" },
  { brand: "KidCo", parent: "KidCo" },
  { brand: "Jool Baby", parent: "Jool Baby" },
  { brand: "Prince Lionheart", parent: "Prince Lionheart" },
  { brand: "Kyte Baby", parent: "Kyte Baby" },
  { brand: "Burt's Bees Baby", parent: "Burt's Bees" },
  { brand: "Copper Pearl", parent: "Copper Pearl" },
  { brand: "aden + anais", parent: "aden + anais" },
  { brand: "Magnetic Me", parent: "Magnetic Me" },
  { brand: "Hanna Andersson", parent: "Hanna Andersson" },
  { brand: "Monica + Andy", parent: "Monica + Andy" },
  { brand: "Goumi Kids", parent: "Goumi" },
  { brand: "Little Sleepies", parent: "Little Sleepies" },
  { brand: "LouLou Lollipop", parent: "LouLou Lollipop" },
  { brand: "MORI", parent: "MORI" },
  { brand: "ergoPouch", parent: "ergoPouch" },
  { brand: "Love to Dream", parent: "Love to Dream" },
  { brand: "Woolino", parent: "Woolino" },
  { brand: "Gunamuna", parent: "Gunamuna" },
  { brand: "Nested Bean", parent: "Nested Bean" },
  { brand: "Snuggle Me Organic", parent: "Snuggle Me Organic" },
  { brand: "DockATot", parent: "DockATot" },
  { brand: "Guava Family", parent: "Guava Family" },
  { brand: "4moms", parent: "Thorley Industries" },
  { brand: "Baby K'tan", parent: "Baby K'tan" },
  { brand: "Munchkin", parent: "Munchkin Inc." },
  { brand: "Green Sprouts", parent: "i play., Inc." },
  { brand: "Nuby", parent: "Luv n' Care" },
  { brand: "Sassy", parent: "Kids2" },
  { brand: "Summer Infant", parent: "Kids2" },
  { brand: "Mustela", parent: "Laboratoires Expanscience" },
  { brand: "Pipette", parent: "Amyris" },
  { brand: "Tubby Todd", parent: "Tubby Todd Bath Co." },
  { brand: "Earth Mama", parent: "Earth Mama Organics" },
  { brand: "Noodle & Boo", parent: "Noodle & Boo" },
  { brand: "Aquaphor Baby", parent: "Beiersdorf" },
  { brand: "CeraVe Baby", parent: "L'Oréal" },
  { brand: "Aveeno Baby", parent: "Kenvue" },
  { brand: "Cetaphil Baby", parent: "Galderma" },
  { brand: "Babyganics", parent: "S.C. Johnson" },
  { brand: "Weleda Baby", parent: "Weleda" },
  { brand: "California Baby", parent: "California Baby" },
  { brand: "Boogie", parent: "Neotech Products" },
  { brand: "NoseFrida", parent: "Frida" },
  { brand: "WubbaNub", parent: "WubbaNub" },
  { brand: "Itzy Ritzy", parent: "Itzy Ritzy" },
  { brand: "Bella Tunno", parent: "Bella Tunno" },
  { brand: "Bumkins", parent: "Bumkins" },
  { brand: "Bumbo", parent: "Bumbo International" },
  { brand: "B.Box", parent: "b.box for kids" },
  { brand: "ezimoov", parent: "ezimoov" },
  { brand: "Lascal", parent: "Lascal" },
  { brand: "phil&teds", parent: "phil&teds" },
  { brand: "Mountain Buggy", parent: "phil&teds" },
  { brand: "Valco Baby", parent: "Valco Baby" },
  { brand: "gb", parent: "Goodbaby International" },
  { brand: "Orbit Baby", parent: "Orbit Baby" },
  { brand: "Leander", parent: "Leander" },
  { brand: "Micuna", parent: "Micuna" },
  { brand: "Ubbi", parent: "Pearhead Inc." },
  { brand: "Pearhead", parent: "Pearhead Inc." },
  { brand: "Baby Shusher", parent: "Baby Shusher LLC" },
  { brand: "Yogasleep Hushh", parent: "Yogasleep" },
  { brand: "Hatch", parent: "Hatch Baby" },
  { brand: "VAVA Baby", parent: "VAVA" },
  { brand: "CuboAi", parent: "CuboAi" },
  { brand: "Sense-U", parent: "Sense-U" },
  { brand: "Levana", parent: "MyKronoz" },
  { brand: "Miku", parent: "Miku Care" },
  { brand: "Eufy Baby", parent: "Anker Innovations" },
  { brand: "JJ Cole", parent: "TOMY International" },
];

/** Lowercased, deduplicated brand + parent-company names for substring matching. */
export const BABY_BRAND_KEYWORDS: string[] = Array.from(
  new Set(
    BABY_BRANDS.flatMap((b) => [b.brand, b.parent])
      .filter((s): s is string => !!s && s.trim().length > 0)
      .map((s) => s.toLowerCase().trim()),
  ),
);
