// Copy (not import) of src/lib/cpscSearch.ts's BABY_KEYWORDS — edge
// functions are a separate deploy target from the main app, per this
// repo's established convention (see recallMatch.ts's header comment).
import { BABY_BRAND_KEYWORDS } from "./babyBrands.ts";

const BABY_CATEGORY_KEYWORDS = [
  "baby",
  "infant",
  "toddler",
  "child",
  "children",
  "kid",
  "kids",
  "nursery",
  "car seat",
  "carseat",
  "stroller",
  "pram",
  "bassinet",
  "crib",
  "cradle",
  "pacifier",
  "soother",
  "bouncer",
  "swing",
  "high chair",
  "highchair",
  "carrier",
  "sling",
  "wrap",
  "swaddle",
  "sleep sack",
  "monitor",
  "formula",
  "breast",
  "bottle",
  "nipple",
  "teether",
  "teething",
  "play mat",
  "playmat",
  "activity mat",
  "jumper",
  "walker",
  "jolly",
  "rocker",
  "boppy",
  "dock a tot",
  "dockatot",
  "snoo",
  "mamaroo",
  "pack n play",
  "pack and play",
  "playard",
  "playpen",
  "baby food",
  "puree",
  "feeding",
  "sippy",
  "diaper",
  "wipe",
  "newborn",
  "preemie",
  "layette",
  "onesie",
  "sleeper",
];

export const BABY_KEYWORDS = Array.from(
  new Set([...BABY_CATEGORY_KEYWORDS, ...BABY_BRAND_KEYWORDS]),
);
