/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedBottlesRouteImport } from './routes/_authenticated/bottles'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedProductsScanRouteImport } from './routes/_authenticated/products.scan'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedMomentsNewRouteImport } from './routes/_authenticated/moments.new'
import { Route as AuthenticatedBottlesNewRouteImport } from './routes/_authenticated/bottles.new'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProductAlertsCheckRouteImport } from './routes/api/public/hooks/product-alerts-check'
import { Route as ApiPublicHooksCpscSyncRouteImport } from './routes/api/public/hooks/cpsc-sync'
import { Route as ApiPublicHooksCheckRecallsRouteImport } from './routes/api/public/hooks/check-recalls'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBottlesRoute = AuthenticatedBottlesRouteImport.update({
  id: '/bottles',
  path: '/bottles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsScanRoute =
  AuthenticatedProductsScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedMomentsNewRoute = AuthenticatedMomentsNewRouteImport.update({
  id: '/moments/new',
  path: '/moments/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBottlesNewRoute = AuthenticatedBottlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBottlesRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProductAlertsCheckRoute =
  ApiPublicHooksProductAlertsCheckRouteImport.update({
    id: '/api/public/hooks/product-alerts-check',
    path: '/api/public/hooks/product-alerts-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCpscSyncRoute = ApiPublicHooksCpscSyncRouteImport.update({
  id: '/api/public/hooks/cpsc-sync',
  path: '/api/public/hooks/cpsc-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckRecallsRoute =
  ApiPublicHooksCheckRecallsRouteImport.update({
    id: '/api/public/hooks/check-recalls',
    path: '/api/public/hooks/check-recalls',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/bottles': typeof AuthenticatedBottlesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/scan': typeof AuthenticatedProductsScanRoute
  '/api/public/hooks/check-recalls': typeof ApiPublicHooksCheckRecallsRoute
  '/api/public/hooks/cpsc-sync': typeof ApiPublicHooksCpscSyncRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/bottles': typeof AuthenticatedBottlesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/scan': typeof AuthenticatedProductsScanRoute
  '/api/public/hooks/check-recalls': typeof ApiPublicHooksCheckRecallsRoute
  '/api/public/hooks/cpsc-sync': typeof ApiPublicHooksCpscSyncRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/terms': typeof TermsRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/bottles': typeof AuthenticatedBottlesRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/_authenticated/moments/new': typeof AuthenticatedMomentsNewRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products/scan': typeof AuthenticatedProductsScanRoute
  '/api/public/hooks/check-recalls': typeof ApiPublicHooksCheckRecallsRoute
  '/api/public/hooks/cpsc-sync': typeof ApiPublicHooksCpscSyncRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/terms'
    | '/add'
    | '/alerts'
    | '/bottles'
    | '/home'
    | '/insights'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/bottles/new'
    | '/moments/new'
    | '/products/new'
    | '/products/scan'
    | '/api/public/hooks/check-recalls'
    | '/api/public/hooks/cpsc-sync'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/terms'
    | '/add'
    | '/alerts'
    | '/bottles'
    | '/home'
    | '/insights'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/bottles/new'
    | '/moments/new'
    | '/products/new'
    | '/products/scan'
    | '/api/public/hooks/check-recalls'
    | '/api/public/hooks/cpsc-sync'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/terms'
    | '/_authenticated/add'
    | '/_authenticated/alerts'
    | '/_authenticated/bottles'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/pricing'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/bottles/new'
    | '/_authenticated/moments/new'
    | '/_authenticated/products/new'
    | '/_authenticated/products/scan'
    | '/api/public/hooks/check-recalls'
    | '/api/public/hooks/cpsc-sync'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksCheckRecallsRoute: typeof ApiPublicHooksCheckRecallsRoute
  ApiPublicHooksCpscSyncRoute: typeof ApiPublicHooksCpscSyncRoute
  ApiPublicHooksProductAlertsCheckRoute: typeof ApiPublicHooksProductAlertsCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bottles': {
      id: '/_authenticated/bottles'
      path: '/bottles'
      fullPath: '/bottles'
      preLoaderRoute: typeof AuthenticatedBottlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/scan': {
      id: '/_authenticated/products/scan'
      path: '/scan'
      fullPath: '/products/scan'
      preLoaderRoute: typeof AuthenticatedProductsScanRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/moments/new': {
      id: '/_authenticated/moments/new'
      path: '/moments/new'
      fullPath: '/moments/new'
      preLoaderRoute: typeof AuthenticatedMomentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bottles/new': {
      id: '/_authenticated/bottles/new'
      path: '/new'
      fullPath: '/bottles/new'
      preLoaderRoute: typeof AuthenticatedBottlesNewRouteImport
      parentRoute: typeof AuthenticatedBottlesRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/product-alerts-check': {
      id: '/api/public/hooks/product-alerts-check'
      path: '/api/public/hooks/product-alerts-check'
      fullPath: '/api/public/hooks/product-alerts-check'
      preLoaderRoute: typeof ApiPublicHooksProductAlertsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cpsc-sync': {
      id: '/api/public/hooks/cpsc-sync'
      path: '/api/public/hooks/cpsc-sync'
      fullPath: '/api/public/hooks/cpsc-sync'
      preLoaderRoute: typeof ApiPublicHooksCpscSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-recalls': {
      id: '/api/public/hooks/check-recalls'
      path: '/api/public/hooks/check-recalls'
      fullPath: '/api/public/hooks/check-recalls'
      preLoaderRoute: typeof ApiPublicHooksCheckRecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBottlesRouteChildren {
  AuthenticatedBottlesNewRoute: typeof AuthenticatedBottlesNewRoute
}

const AuthenticatedBottlesRouteChildren: AuthenticatedBottlesRouteChildren = {
  AuthenticatedBottlesNewRoute: AuthenticatedBottlesNewRoute,
}

const AuthenticatedBottlesRouteWithChildren =
  AuthenticatedBottlesRoute._addFileChildren(AuthenticatedBottlesRouteChildren)

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsScanRoute: typeof AuthenticatedProductsScanRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsScanRoute: AuthenticatedProductsScanRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBottlesRoute: typeof AuthenticatedBottlesRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMomentsNewRoute: typeof AuthenticatedMomentsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBottlesRoute: AuthenticatedBottlesRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMomentsNewRoute: AuthenticatedMomentsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksCheckRecallsRoute: ApiPublicHooksCheckRecallsRoute,
  ApiPublicHooksCpscSyncRoute: ApiPublicHooksCpscSyncRoute,
  ApiPublicHooksProductAlertsCheckRoute: ApiPublicHooksProductAlertsCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
