/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RecallsRouteImport } from './routes/recalls'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MomentsTimelinePreviewRouteImport } from './routes/moments-timeline-preview'
import { Route as MomentsIconOptionsPreviewRouteImport } from './routes/moments-icon-options-preview'
import { Route as MomentsIconOptions3PreviewRouteImport } from './routes/moments-icon-options-3-preview'
import { Route as MomentsIconOptions2PreviewRouteImport } from './routes/moments-icon-options-2-preview'
import { Route as MomentsHanddrawnPreviewRouteImport } from './routes/moments-handdrawn-preview'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmergencyShareTokenRouteImport } from './routes/emergency-share.$token'
import { Route as CaregiverInviteTokenRouteImport } from './routes/caregiver-invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTravelChecklistRouteImport } from './routes/_authenticated/travel-checklist'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedSafetyGuidesRouteImport } from './routes/_authenticated/safety-guides'
import { Route as AuthenticatedRegistryCheckRouteImport } from './routes/_authenticated/registry-check'
import { Route as AuthenticatedRecallRadarRouteImport } from './routes/_authenticated/recall-radar'
import { Route as AuthenticatedRecallCheckRouteImport } from './routes/_authenticated/recall-check'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedMomentsRouteImport } from './routes/_authenticated/moments'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFirstFoodsRouteImport } from './routes/_authenticated/first-foods'
import { Route as AuthenticatedEmergencyInfoRouteImport } from './routes/_authenticated/emergency-info'
import { Route as AuthenticatedChecklistsRouteImport } from './routes/_authenticated/checklists'
import { Route as AuthenticatedCaregiverCardRouteImport } from './routes/_authenticated/caregiver-card'
import { Route as AuthenticatedBottlesRouteImport } from './routes/_authenticated/bottles'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as ApiPublicEmergencyShareRouteImport } from './routes/api/public/emergency-share'
import { Route as ApiPublicCaregiverInviteRouteImport } from './routes/api/public/caregiver-invite'
import { Route as AuthenticatedProfileSupportRouteImport } from './routes/_authenticated/profile_.support'
import { Route as AuthenticatedProfilePrivacyPromiseRouteImport } from './routes/_authenticated/profile_/privacy-promise'
import { Route as AuthenticatedProfilePrivacyPolicyRouteImport } from './routes/_authenticated/profile_.privacy-policy'
import { Route as AuthenticatedProfileNotificationSettingsRouteImport } from './routes/_authenticated/profile_.notification-settings'
import { Route as AuthenticatedProductsScanRouteImport } from './routes/_authenticated/products_.scan'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products_.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products_.$id'
import { Route as AuthenticatedMomentsNewRouteImport } from './routes/_authenticated/moments_.new'
import { Route as AuthenticatedBottlesNewRouteImport } from './routes/_authenticated/bottles_.new'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProductAlertsCheckRouteImport } from './routes/api/public/hooks/product-alerts-check'
import { Route as ApiPublicHooksCheckProductAlertsRouteImport } from './routes/api/public/hooks/check-product-alerts'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsRoute = RecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsTimelinePreviewRoute = MomentsTimelinePreviewRouteImport.update({
  id: '/moments-timeline-preview',
  path: '/moments-timeline-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsIconOptionsPreviewRoute =
  MomentsIconOptionsPreviewRouteImport.update({
    id: '/moments-icon-options-preview',
    path: '/moments-icon-options-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const MomentsIconOptions3PreviewRoute =
  MomentsIconOptions3PreviewRouteImport.update({
    id: '/moments-icon-options-3-preview',
    path: '/moments-icon-options-3-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const MomentsIconOptions2PreviewRoute =
  MomentsIconOptions2PreviewRouteImport.update({
    id: '/moments-icon-options-2-preview',
    path: '/moments-icon-options-2-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const MomentsHanddrawnPreviewRoute = MomentsHanddrawnPreviewRouteImport.update({
  id: '/moments-handdrawn-preview',
  path: '/moments-handdrawn-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyShareTokenRoute = EmergencyShareTokenRouteImport.update({
  id: '/emergency-share/$token',
  path: '/emergency-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverInviteTokenRoute = CaregiverInviteTokenRouteImport.update({
  id: '/caregiver-invite/$token',
  path: '/caregiver-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTravelChecklistRoute =
  AuthenticatedTravelChecklistRouteImport.update({
    id: '/travel-checklist',
    path: '/travel-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyGuidesRoute =
  AuthenticatedSafetyGuidesRouteImport.update({
    id: '/safety-guides',
    path: '/safety-guides',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistryCheckRoute =
  AuthenticatedRegistryCheckRouteImport.update({
    id: '/registry-check',
    path: '/registry-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecallRadarRoute =
  AuthenticatedRecallRadarRouteImport.update({
    id: '/recall-radar',
    path: '/recall-radar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecallCheckRoute =
  AuthenticatedRecallCheckRouteImport.update({
    id: '/recall-check',
    path: '/recall-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsRoute = AuthenticatedMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstFoodsRoute = AuthenticatedFirstFoodsRouteImport.update({
  id: '/first-foods',
  path: '/first-foods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyInfoRoute =
  AuthenticatedEmergencyInfoRouteImport.update({
    id: '/emergency-info',
    path: '/emergency-info',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsRoute = AuthenticatedChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaregiverCardRoute =
  AuthenticatedCaregiverCardRouteImport.update({
    id: '/caregiver-card',
    path: '/caregiver-card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBottlesRoute = AuthenticatedBottlesRouteImport.update({
  id: '/bottles',
  path: '/bottles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicEmergencyShareRoute = ApiPublicEmergencyShareRouteImport.update({
  id: '/api/public/emergency-share',
  path: '/api/public/emergency-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaregiverInviteRoute =
  ApiPublicCaregiverInviteRouteImport.update({
    id: '/api/public/caregiver-invite',
    path: '/api/public/caregiver-invite',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileSupportRoute =
  AuthenticatedProfileSupportRouteImport.update({
    id: '/profile_/support',
    path: '/profile/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilePrivacyPromiseRoute =
  AuthenticatedProfilePrivacyPromiseRouteImport.update({
    id: '/profile_/privacy-promise',
    path: '/profile/privacy-promise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilePrivacyPolicyRoute =
  AuthenticatedProfilePrivacyPolicyRouteImport.update({
    id: '/profile_/privacy-policy',
    path: '/profile/privacy-policy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileNotificationSettingsRoute =
  AuthenticatedProfileNotificationSettingsRouteImport.update({
    id: '/profile_/notification-settings',
    path: '/profile/notification-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsScanRoute =
  AuthenticatedProductsScanRouteImport.update({
    id: '/products_/scan',
    path: '/products/scan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products_/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsNewRoute = AuthenticatedMomentsNewRouteImport.update({
  id: '/moments_/new',
  path: '/moments/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBottlesNewRoute = AuthenticatedBottlesNewRouteImport.update({
  id: '/bottles_/new',
  path: '/bottles/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProductAlertsCheckRoute =
  ApiPublicHooksProductAlertsCheckRouteImport.update({
    id: '/api/public/hooks/product-alerts-check',
    path: '/api/public/hooks/product-alerts-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckProductAlertsRoute =
  ApiPublicHooksCheckProductAlertsRouteImport.update({
    id: '/api/public/hooks/check-product-alerts',
    path: '/api/public/hooks/check-product-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/design-preview': typeof DesignPreviewRoute
  '/moments-handdrawn-preview': typeof MomentsHanddrawnPreviewRoute
  '/moments-icon-options-2-preview': typeof MomentsIconOptions2PreviewRoute
  '/moments-icon-options-3-preview': typeof MomentsIconOptions3PreviewRoute
  '/moments-icon-options-preview': typeof MomentsIconOptionsPreviewRoute
  '/moments-timeline-preview': typeof MomentsTimelinePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/recalls': typeof RecallsRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/bottles': typeof AuthenticatedBottlesRoute
  '/caregiver-card': typeof AuthenticatedCaregiverCardRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/emergency-info': typeof AuthenticatedEmergencyInfoRoute
  '/first-foods': typeof AuthenticatedFirstFoodsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recall-check': typeof AuthenticatedRecallCheckRoute
  '/recall-radar': typeof AuthenticatedRecallRadarRoute
  '/registry-check': typeof AuthenticatedRegistryCheckRoute
  '/safety-guides': typeof AuthenticatedSafetyGuidesRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/travel-checklist': typeof AuthenticatedTravelChecklistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/caregiver-invite/$token': typeof CaregiverInviteTokenRoute
  '/emergency-share/$token': typeof EmergencyShareTokenRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/scan': typeof AuthenticatedProductsScanRoute
  '/profile/notification-settings': typeof AuthenticatedProfileNotificationSettingsRoute
  '/profile/privacy-policy': typeof AuthenticatedProfilePrivacyPolicyRoute
  '/profile/privacy-promise': typeof AuthenticatedProfilePrivacyPromiseRoute
  '/profile/support': typeof AuthenticatedProfileSupportRoute
  '/api/public/caregiver-invite': typeof ApiPublicCaregiverInviteRoute
  '/api/public/emergency-share': typeof ApiPublicEmergencyShareRoute
  '/api/public/hooks/check-product-alerts': typeof ApiPublicHooksCheckProductAlertsRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/design-preview': typeof DesignPreviewRoute
  '/moments-handdrawn-preview': typeof MomentsHanddrawnPreviewRoute
  '/moments-icon-options-2-preview': typeof MomentsIconOptions2PreviewRoute
  '/moments-icon-options-3-preview': typeof MomentsIconOptions3PreviewRoute
  '/moments-icon-options-preview': typeof MomentsIconOptionsPreviewRoute
  '/moments-timeline-preview': typeof MomentsTimelinePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/recalls': typeof RecallsRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/bottles': typeof AuthenticatedBottlesRoute
  '/caregiver-card': typeof AuthenticatedCaregiverCardRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/emergency-info': typeof AuthenticatedEmergencyInfoRoute
  '/first-foods': typeof AuthenticatedFirstFoodsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recall-check': typeof AuthenticatedRecallCheckRoute
  '/recall-radar': typeof AuthenticatedRecallRadarRoute
  '/registry-check': typeof AuthenticatedRegistryCheckRoute
  '/safety-guides': typeof AuthenticatedSafetyGuidesRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/travel-checklist': typeof AuthenticatedTravelChecklistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/caregiver-invite/$token': typeof CaregiverInviteTokenRoute
  '/emergency-share/$token': typeof EmergencyShareTokenRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/moments/new': typeof AuthenticatedMomentsNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/scan': typeof AuthenticatedProductsScanRoute
  '/profile/notification-settings': typeof AuthenticatedProfileNotificationSettingsRoute
  '/profile/privacy-policy': typeof AuthenticatedProfilePrivacyPolicyRoute
  '/profile/privacy-promise': typeof AuthenticatedProfilePrivacyPromiseRoute
  '/profile/support': typeof AuthenticatedProfileSupportRoute
  '/api/public/caregiver-invite': typeof ApiPublicCaregiverInviteRoute
  '/api/public/emergency-share': typeof ApiPublicEmergencyShareRoute
  '/api/public/hooks/check-product-alerts': typeof ApiPublicHooksCheckProductAlertsRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design-preview': typeof DesignPreviewRoute
  '/moments-handdrawn-preview': typeof MomentsHanddrawnPreviewRoute
  '/moments-icon-options-2-preview': typeof MomentsIconOptions2PreviewRoute
  '/moments-icon-options-3-preview': typeof MomentsIconOptions3PreviewRoute
  '/moments-icon-options-preview': typeof MomentsIconOptionsPreviewRoute
  '/moments-timeline-preview': typeof MomentsTimelinePreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/recalls': typeof RecallsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/bottles': typeof AuthenticatedBottlesRoute
  '/_authenticated/caregiver-card': typeof AuthenticatedCaregiverCardRoute
  '/_authenticated/checklists': typeof AuthenticatedChecklistsRoute
  '/_authenticated/emergency-info': typeof AuthenticatedEmergencyInfoRoute
  '/_authenticated/first-foods': typeof AuthenticatedFirstFoodsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/moments': typeof AuthenticatedMomentsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recall-check': typeof AuthenticatedRecallCheckRoute
  '/_authenticated/recall-radar': typeof AuthenticatedRecallRadarRoute
  '/_authenticated/registry-check': typeof AuthenticatedRegistryCheckRoute
  '/_authenticated/safety-guides': typeof AuthenticatedSafetyGuidesRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/travel-checklist': typeof AuthenticatedTravelChecklistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/caregiver-invite/$token': typeof CaregiverInviteTokenRoute
  '/emergency-share/$token': typeof EmergencyShareTokenRoute
  '/_authenticated/bottles_/new': typeof AuthenticatedBottlesNewRoute
  '/_authenticated/moments_/new': typeof AuthenticatedMomentsNewRoute
  '/_authenticated/products_/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products_/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products_/scan': typeof AuthenticatedProductsScanRoute
  '/_authenticated/profile_/notification-settings': typeof AuthenticatedProfileNotificationSettingsRoute
  '/_authenticated/profile_/privacy-policy': typeof AuthenticatedProfilePrivacyPolicyRoute
  '/_authenticated/profile_/privacy-promise': typeof AuthenticatedProfilePrivacyPromiseRoute
  '/_authenticated/profile_/support': typeof AuthenticatedProfileSupportRoute
  '/api/public/caregiver-invite': typeof ApiPublicCaregiverInviteRoute
  '/api/public/emergency-share': typeof ApiPublicEmergencyShareRoute
  '/api/public/hooks/check-product-alerts': typeof ApiPublicHooksCheckProductAlertsRoute
  '/api/public/hooks/product-alerts-check': typeof ApiPublicHooksProductAlertsCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/design-preview'
    | '/moments-handdrawn-preview'
    | '/moments-icon-options-2-preview'
    | '/moments-icon-options-3-preview'
    | '/moments-icon-options-preview'
    | '/moments-timeline-preview'
    | '/onboarding'
    | '/recalls'
    | '/terms'
    | '/add'
    | '/alerts'
    | '/bottles'
    | '/caregiver-card'
    | '/checklists'
    | '/emergency-info'
    | '/first-foods'
    | '/home'
    | '/moments'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/recall-check'
    | '/recall-radar'
    | '/registry-check'
    | '/safety-guides'
    | '/tracking'
    | '/travel-checklist'
    | '/auth/callback'
    | '/caregiver-invite/$token'
    | '/emergency-share/$token'
    | '/bottles/new'
    | '/moments/new'
    | '/products/$id'
    | '/products/new'
    | '/products/scan'
    | '/profile/notification-settings'
    | '/profile/privacy-policy'
    | '/profile/privacy-promise'
    | '/profile/support'
    | '/api/public/caregiver-invite'
    | '/api/public/emergency-share'
    | '/api/public/hooks/check-product-alerts'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/design-preview'
    | '/moments-handdrawn-preview'
    | '/moments-icon-options-2-preview'
    | '/moments-icon-options-3-preview'
    | '/moments-icon-options-preview'
    | '/moments-timeline-preview'
    | '/onboarding'
    | '/recalls'
    | '/terms'
    | '/add'
    | '/alerts'
    | '/bottles'
    | '/caregiver-card'
    | '/checklists'
    | '/emergency-info'
    | '/first-foods'
    | '/home'
    | '/moments'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/recall-check'
    | '/recall-radar'
    | '/registry-check'
    | '/safety-guides'
    | '/tracking'
    | '/travel-checklist'
    | '/auth/callback'
    | '/caregiver-invite/$token'
    | '/emergency-share/$token'
    | '/bottles/new'
    | '/moments/new'
    | '/products/$id'
    | '/products/new'
    | '/products/scan'
    | '/profile/notification-settings'
    | '/profile/privacy-policy'
    | '/profile/privacy-promise'
    | '/profile/support'
    | '/api/public/caregiver-invite'
    | '/api/public/emergency-share'
    | '/api/public/hooks/check-product-alerts'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/design-preview'
    | '/moments-handdrawn-preview'
    | '/moments-icon-options-2-preview'
    | '/moments-icon-options-3-preview'
    | '/moments-icon-options-preview'
    | '/moments-timeline-preview'
    | '/onboarding'
    | '/recalls'
    | '/terms'
    | '/_authenticated/add'
    | '/_authenticated/alerts'
    | '/_authenticated/bottles'
    | '/_authenticated/caregiver-card'
    | '/_authenticated/checklists'
    | '/_authenticated/emergency-info'
    | '/_authenticated/first-foods'
    | '/_authenticated/home'
    | '/_authenticated/moments'
    | '/_authenticated/pricing'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/recall-check'
    | '/_authenticated/recall-radar'
    | '/_authenticated/registry-check'
    | '/_authenticated/safety-guides'
    | '/_authenticated/tracking'
    | '/_authenticated/travel-checklist'
    | '/auth/callback'
    | '/caregiver-invite/$token'
    | '/emergency-share/$token'
    | '/_authenticated/bottles_/new'
    | '/_authenticated/moments_/new'
    | '/_authenticated/products_/$id'
    | '/_authenticated/products_/new'
    | '/_authenticated/products_/scan'
    | '/_authenticated/profile_/notification-settings'
    | '/_authenticated/profile_/privacy-policy'
    | '/_authenticated/profile_/privacy-promise'
    | '/_authenticated/profile_/support'
    | '/api/public/caregiver-invite'
    | '/api/public/emergency-share'
    | '/api/public/hooks/check-product-alerts'
    | '/api/public/hooks/product-alerts-check'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignPreviewRoute: typeof DesignPreviewRoute
  MomentsHanddrawnPreviewRoute: typeof MomentsHanddrawnPreviewRoute
  MomentsIconOptions2PreviewRoute: typeof MomentsIconOptions2PreviewRoute
  MomentsIconOptions3PreviewRoute: typeof MomentsIconOptions3PreviewRoute
  MomentsIconOptionsPreviewRoute: typeof MomentsIconOptionsPreviewRoute
  MomentsTimelinePreviewRoute: typeof MomentsTimelinePreviewRoute
  OnboardingRoute: typeof OnboardingRoute
  RecallsRoute: typeof RecallsRoute
  TermsRoute: typeof TermsRoute
  CaregiverInviteTokenRoute: typeof CaregiverInviteTokenRoute
  EmergencyShareTokenRoute: typeof EmergencyShareTokenRoute
  ApiPublicCaregiverInviteRoute: typeof ApiPublicCaregiverInviteRoute
  ApiPublicEmergencyShareRoute: typeof ApiPublicEmergencyShareRoute
  ApiPublicHooksCheckProductAlertsRoute: typeof ApiPublicHooksCheckProductAlertsRoute
  ApiPublicHooksProductAlertsCheckRoute: typeof ApiPublicHooksProductAlertsCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls': {
      id: '/recalls'
      path: '/recalls'
      fullPath: '/recalls'
      preLoaderRoute: typeof RecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments-timeline-preview': {
      id: '/moments-timeline-preview'
      path: '/moments-timeline-preview'
      fullPath: '/moments-timeline-preview'
      preLoaderRoute: typeof MomentsTimelinePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments-icon-options-preview': {
      id: '/moments-icon-options-preview'
      path: '/moments-icon-options-preview'
      fullPath: '/moments-icon-options-preview'
      preLoaderRoute: typeof MomentsIconOptionsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments-icon-options-3-preview': {
      id: '/moments-icon-options-3-preview'
      path: '/moments-icon-options-3-preview'
      fullPath: '/moments-icon-options-3-preview'
      preLoaderRoute: typeof MomentsIconOptions3PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments-icon-options-2-preview': {
      id: '/moments-icon-options-2-preview'
      path: '/moments-icon-options-2-preview'
      fullPath: '/moments-icon-options-2-preview'
      preLoaderRoute: typeof MomentsIconOptions2PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments-handdrawn-preview': {
      id: '/moments-handdrawn-preview'
      path: '/moments-handdrawn-preview'
      fullPath: '/moments-handdrawn-preview'
      preLoaderRoute: typeof MomentsHanddrawnPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-share/$token': {
      id: '/emergency-share/$token'
      path: '/emergency-share/$token'
      fullPath: '/emergency-share/$token'
      preLoaderRoute: typeof EmergencyShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver-invite/$token': {
      id: '/caregiver-invite/$token'
      path: '/caregiver-invite/$token'
      fullPath: '/caregiver-invite/$token'
      preLoaderRoute: typeof CaregiverInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/travel-checklist': {
      id: '/_authenticated/travel-checklist'
      path: '/travel-checklist'
      fullPath: '/travel-checklist'
      preLoaderRoute: typeof AuthenticatedTravelChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety-guides': {
      id: '/_authenticated/safety-guides'
      path: '/safety-guides'
      fullPath: '/safety-guides'
      preLoaderRoute: typeof AuthenticatedSafetyGuidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registry-check': {
      id: '/_authenticated/registry-check'
      path: '/registry-check'
      fullPath: '/registry-check'
      preLoaderRoute: typeof AuthenticatedRegistryCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recall-radar': {
      id: '/_authenticated/recall-radar'
      path: '/recall-radar'
      fullPath: '/recall-radar'
      preLoaderRoute: typeof AuthenticatedRecallRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recall-check': {
      id: '/_authenticated/recall-check'
      path: '/recall-check'
      fullPath: '/recall-check'
      preLoaderRoute: typeof AuthenticatedRecallCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments': {
      id: '/_authenticated/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedMomentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-foods': {
      id: '/_authenticated/first-foods'
      path: '/first-foods'
      fullPath: '/first-foods'
      preLoaderRoute: typeof AuthenticatedFirstFoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency-info': {
      id: '/_authenticated/emergency-info'
      path: '/emergency-info'
      fullPath: '/emergency-info'
      preLoaderRoute: typeof AuthenticatedEmergencyInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists': {
      id: '/_authenticated/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthenticatedChecklistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver-card': {
      id: '/_authenticated/caregiver-card'
      path: '/caregiver-card'
      fullPath: '/caregiver-card'
      preLoaderRoute: typeof AuthenticatedCaregiverCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bottles': {
      id: '/_authenticated/bottles'
      path: '/bottles'
      fullPath: '/bottles'
      preLoaderRoute: typeof AuthenticatedBottlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/emergency-share': {
      id: '/api/public/emergency-share'
      path: '/api/public/emergency-share'
      fullPath: '/api/public/emergency-share'
      preLoaderRoute: typeof ApiPublicEmergencyShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caregiver-invite': {
      id: '/api/public/caregiver-invite'
      path: '/api/public/caregiver-invite'
      fullPath: '/api/public/caregiver-invite'
      preLoaderRoute: typeof ApiPublicCaregiverInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile_/support': {
      id: '/_authenticated/profile_/support'
      path: '/profile/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof AuthenticatedProfileSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/privacy-promise': {
      id: '/_authenticated/profile_/privacy-promise'
      path: '/profile/privacy-promise'
      fullPath: '/profile/privacy-promise'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyPromiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/privacy-policy': {
      id: '/_authenticated/profile_/privacy-policy'
      path: '/profile/privacy-policy'
      fullPath: '/profile/privacy-policy'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyPolicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/notification-settings': {
      id: '/_authenticated/profile_/notification-settings'
      path: '/profile/notification-settings'
      fullPath: '/profile/notification-settings'
      preLoaderRoute: typeof AuthenticatedProfileNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products_/scan': {
      id: '/_authenticated/products_/scan'
      path: '/products/scan'
      fullPath: '/products/scan'
      preLoaderRoute: typeof AuthenticatedProductsScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products_/new': {
      id: '/_authenticated/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products_/$id': {
      id: '/_authenticated/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments_/new': {
      id: '/_authenticated/moments_/new'
      path: '/moments/new'
      fullPath: '/moments/new'
      preLoaderRoute: typeof AuthenticatedMomentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bottles_/new': {
      id: '/_authenticated/bottles_/new'
      path: '/bottles/new'
      fullPath: '/bottles/new'
      preLoaderRoute: typeof AuthenticatedBottlesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/product-alerts-check': {
      id: '/api/public/hooks/product-alerts-check'
      path: '/api/public/hooks/product-alerts-check'
      fullPath: '/api/public/hooks/product-alerts-check'
      preLoaderRoute: typeof ApiPublicHooksProductAlertsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-product-alerts': {
      id: '/api/public/hooks/check-product-alerts'
      path: '/api/public/hooks/check-product-alerts'
      fullPath: '/api/public/hooks/check-product-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckProductAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBottlesRoute: typeof AuthenticatedBottlesRoute
  AuthenticatedCaregiverCardRoute: typeof AuthenticatedCaregiverCardRoute
  AuthenticatedChecklistsRoute: typeof AuthenticatedChecklistsRoute
  AuthenticatedEmergencyInfoRoute: typeof AuthenticatedEmergencyInfoRoute
  AuthenticatedFirstFoodsRoute: typeof AuthenticatedFirstFoodsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMomentsRoute: typeof AuthenticatedMomentsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecallCheckRoute: typeof AuthenticatedRecallCheckRoute
  AuthenticatedRecallRadarRoute: typeof AuthenticatedRecallRadarRoute
  AuthenticatedRegistryCheckRoute: typeof AuthenticatedRegistryCheckRoute
  AuthenticatedSafetyGuidesRoute: typeof AuthenticatedSafetyGuidesRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedTravelChecklistRoute: typeof AuthenticatedTravelChecklistRoute
  AuthenticatedBottlesNewRoute: typeof AuthenticatedBottlesNewRoute
  AuthenticatedMomentsNewRoute: typeof AuthenticatedMomentsNewRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsScanRoute: typeof AuthenticatedProductsScanRoute
  AuthenticatedProfileNotificationSettingsRoute: typeof AuthenticatedProfileNotificationSettingsRoute
  AuthenticatedProfilePrivacyPolicyRoute: typeof AuthenticatedProfilePrivacyPolicyRoute
  AuthenticatedProfilePrivacyPromiseRoute: typeof AuthenticatedProfilePrivacyPromiseRoute
  AuthenticatedProfileSupportRoute: typeof AuthenticatedProfileSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBottlesRoute: AuthenticatedBottlesRoute,
  AuthenticatedCaregiverCardRoute: AuthenticatedCaregiverCardRoute,
  AuthenticatedChecklistsRoute: AuthenticatedChecklistsRoute,
  AuthenticatedEmergencyInfoRoute: AuthenticatedEmergencyInfoRoute,
  AuthenticatedFirstFoodsRoute: AuthenticatedFirstFoodsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMomentsRoute: AuthenticatedMomentsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecallCheckRoute: AuthenticatedRecallCheckRoute,
  AuthenticatedRecallRadarRoute: AuthenticatedRecallRadarRoute,
  AuthenticatedRegistryCheckRoute: AuthenticatedRegistryCheckRoute,
  AuthenticatedSafetyGuidesRoute: AuthenticatedSafetyGuidesRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedTravelChecklistRoute: AuthenticatedTravelChecklistRoute,
  AuthenticatedBottlesNewRoute: AuthenticatedBottlesNewRoute,
  AuthenticatedMomentsNewRoute: AuthenticatedMomentsNewRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsScanRoute: AuthenticatedProductsScanRoute,
  AuthenticatedProfileNotificationSettingsRoute:
    AuthenticatedProfileNotificationSettingsRoute,
  AuthenticatedProfilePrivacyPolicyRoute:
    AuthenticatedProfilePrivacyPolicyRoute,
  AuthenticatedProfilePrivacyPromiseRoute:
    AuthenticatedProfilePrivacyPromiseRoute,
  AuthenticatedProfileSupportRoute: AuthenticatedProfileSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignPreviewRoute: DesignPreviewRoute,
  MomentsHanddrawnPreviewRoute: MomentsHanddrawnPreviewRoute,
  MomentsIconOptions2PreviewRoute: MomentsIconOptions2PreviewRoute,
  MomentsIconOptions3PreviewRoute: MomentsIconOptions3PreviewRoute,
  MomentsIconOptionsPreviewRoute: MomentsIconOptionsPreviewRoute,
  MomentsTimelinePreviewRoute: MomentsTimelinePreviewRoute,
  OnboardingRoute: OnboardingRoute,
  RecallsRoute: RecallsRoute,
  TermsRoute: TermsRoute,
  CaregiverInviteTokenRoute: CaregiverInviteTokenRoute,
  EmergencyShareTokenRoute: EmergencyShareTokenRoute,
  ApiPublicCaregiverInviteRoute: ApiPublicCaregiverInviteRoute,
  ApiPublicEmergencyShareRoute: ApiPublicEmergencyShareRoute,
  ApiPublicHooksCheckProductAlertsRoute: ApiPublicHooksCheckProductAlertsRoute,
  ApiPublicHooksProductAlertsCheckRoute: ApiPublicHooksProductAlertsCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
